theme: jekyll-theme-minimal
title: Lekoro's python portfolio
description: Tech consultant and builder of modern platforms. I help startups turn code into business and small businesses turn code into money.
url: "https://lnkholise.github.io"
author: Lekoro Leonard Nkholise
social_links:
  github: https://github.com/LNkholise
  linkedin: https://linkedin.com/in/lekoro-leonard-nkholise
